insert into "ProxyCountries" (code,name) 
values ('AU','Australia'),
('CN','China'),
('JP','Japan'),
('TH','Thailand'),
('US','United States'),
('IN','India'),
('MY','Malaysia'),
('KR','Korea, Republic of'),
('SG','Singapore'),
('HK','Hong Kong'),
('TW','Taiwan'),
('PH','Philippines'),
('VN','Vietnam'),
('FR','France'),
('EU','Europe'),
('DE','Germany'),
('GB','United Kingdom'),
('SE','Sweden'),
('IT','Italy'),
('NL','Netherlands'),
('GR','Greece'),
('ES','Spain'),
('AT','Austria'),
('BE','Belgium'),
('AE','United Arab Emirates'),
('IL','Israel'),
('RU','Russian Federation'),
('DK','Denmark'),
('KZ','Kazakhstan'),
('PT','Portugal'),
('SA','Saudi Arabia'),
('IR','Iran, Islamic Republic of'),
('NO','Norway'),
('CA','Canada'),
('MX','Mexico'),
('SY','Syrian Arab Republic'),
('UA','Ukraine'),
('KW','Kuwait'),
('BH','Bahrain'),
('LB','Lebanon'),
('QA','Qatar'),
('OM','Oman'),
('JO','Jordan'),
('CZ','Czech Republic'),
('CH','Switzerland'),
('IQ','Iraq'),
('TR','Turkey'),
('RO','Romania'),
('PA','Panama'),
('BR','Brazil'),
('CL','Chile'),
('AR','Argentina'),
('CO','Colombia'),
('PL','Poland'),
('FI','Finland'),
('GE','Georgia'),
('AZ','Azerbaijan'),
('PS','Palestinian Territory'),
('LT','Lithuania'),
('SK','Slovakia'),
('RS','Serbia'),
('HU','Hungary'),
('LU','Luxembourg'),
('IS','Iceland'),
('BG','Bulgaria'),
('SI','Slovenia'),
('MD','Moldova, Republic of'),
('MK','Macedonia'),
('IE','Ireland'),
('LI','Liechtenstein'),
('JE','Jersey'),
('HR','Croatia'),
('PK','Pakistan'),
('BA','Bosnia and Herzegovina'),
('PY','Paraguay'),
('EE','Estonia'),
('LV','Latvia'),
('KG','Kyrgyzstan'),
('RE','Reunion'),
('TJ','Tajikistan'),
('ID','Indonesia'),
('AS','American Samoa'),
('AI','Anguilla'),
('AG','Antigua and Barbuda'),
('AW','Aruba'),
('BS','Bahamas'),
('BB','Barbados'),
('BZ','Belize'),
('BM','Bermuda'),
('BO','Bolivia'),
('VG','Virgin Islands, British'),
('KY','Cayman Islands'),
('CK','Cook Islands'),
('CR','Costa Rica'),
('CU','Cuba'),
('DM','Dominica'),
('DO','Dominican Republic'),
('EC','Ecuador'),
('SV','El Salvador'),
('FK','Falkland Islands (Malvinas)'),
('FJ','Fiji'),
('GD','Grenada'),
('GP','Guadeloupe'),
('GU','Guam'),
('GT','Guatemala'),
('GY','Guyana'),
('HT','Haiti'),
('HN','Honduras'),
('JM','Jamaica'),
('KI','Kiribati'),
('MS','Montserrat'),
('NR','Nauru'),
('NC','New Caledonia'),
('NI','Nicaragua'),
('NU','Niue'),
('NF','Norfolk Island'),
('KP','Korea, Democratic People''s Republic of'),
('PW','Palau'),
('PG','Papua New Guinea'),
('PE','Peru'),
('PN','Pitcairn Islands'),
('PR','Puerto Rico'),
('KN','Saint Kitts and Nevis'),
('LC','Saint Lucia'),
('VC','Saint Vincent and the Grenadines'),
('WS','Samoa'),
('SB','Solomon Islands'),
('SR','Suriname'),
('SZ','Swaziland'),
('TT','Trinidad and Tobago'),
('TC','Turks and Caicos Islands'),
('TV','Tuvalu'),
('UY','Uruguay'),
('VU','Vanuatu'),
('VE','Venezuela'),
('PM','Saint Pierre and Miquelon'),
('AD','Andorra'),
('AO','Angola'),
('AM','Armenia'),
('BD','Bangladesh'),
('BY','Belarus'),
('BJ','Benin'),
('BT','Bhutan'),
('BW','Botswana'),
('BN','Brunei Darussalam'),
('BF','Burkina Faso'),
('BI','Burundi'),
('KH','Cambodia'),
('CM','Cameroon'),
('CV','Cape Verde'),
('CF','Central African Republic'),
('TD','Chad'),
('CX','Christmas Island'),
('CC','Cocos (Keeling) Islands'),
('KM','Comoros'),
('CD','Congo, The Democratic Republic of the'),
('CI','Cote D''Ivoire'),
('CY','Cyprus'),
('EG','Egypt'),
('GQ','Equatorial Guinea'),
('ER','Eritrea'),
('ET','Ethiopia'),
('FO','Faroe Islands'),
('GA','Gabon'),
('GM','Gambia'),
('GH','Ghana'),
('GI','Gibraltar'),
('GL','Greenland'),
('GW','Guinea-Bissau'),
('GN','Guinea'),
('KE','Kenya'),
('LA','Lao People''s Democratic Republic'),
('LS','Lesotho'),
('LR','Liberia'),
('LY','Libya'),
('MO','Macau'),
('MG','Madagascar'),
('MW','Malawi'),
('MV','Maldives'),
('ML','Mali'),
('MN','Mongolia'),
('MT','Malta'),
('MR','Mauritania'),
('MU','Mauritius'),
('MC','Monaco'),
('ME','Montenegro'),
('MA','Morocco'),
('MZ','Mozambique'),
('MM','Myanmar'),
('NA','Namibia'),
('NP','Nepal'),
('NE','Niger'),
('NG','Nigeria'),
('DJ','Djibouti'),
('CG','Congo'),
('RW','Rwanda'),
('SH','Saint Helena'),
('SM','San Marino'),
('ST','Sao Tome and Principe'),
('SN','Senegal'),
('SL','Sierra Leone'),
('SO','Somalia'),
('LK','Sri Lanka'),
('SD','Sudan'),
('SJ','Svalbard and Jan Mayen'),
('TZ','Tanzania, United Republic of'),
('TG','Togo'),
('TN','Tunisia'),
('TM','Turkmenistan'),
('UG','Uganda'),
('UZ','Uzbekistan'),
('VA','Holy See (Vatican City State)'),
('YE','Yemen'),
('ZM','Zambia'),
('ZW','Zimbabwe'),
('AF','Afghanistan'),
('AL','Albania'),
('DZ','Algeria'),
('AX','Aland Islands'),
('IM','Isle of Man'),
('GG','Guernsey'),
('MQ','Martinique'),
('A2','Satellite Provider'),
('ZA','South Africa'),
('MP','Northern Mariana Islands'),
('VI','Virgin Islands, U.S.'),
('UM','United States Minor Outlying Islands'),
('NZ','New Zealand'),
('AP','Asia/Pacific Region'),
('TK','Tokelau'),
('WF','Wallis and Futuna'),
('A1','Anonymous Proxy'),
('BV','Bouvet Island'),
('AQ','Antarctica'),
('SC','Seychelles'),
('MF','Saint Martin'),
('SS','South Sudan'),
('YT','Mayotte'),
('FM','Micronesia, Federated States of'),
('PF','French Polynesia'),
('TL','Timor-Leste'),
('TO','Tonga'),
('TF','French Southern Territories'),
('CW','Curacao'),
('MH','Marshall Islands'),
('HM','Heard Island and McDonald Islands'),
('GS','South Georgia and the South Sandwich Islands'),
('SX','Sint Maarten (Dutch part)'),
('BL','Saint Barthelemy'),
('BQ','Bonaire, Saint Eustatius and Saba'),
('GF','French Guiana'),
('EH','Western Sahara'),
('IO','British Indian Ocean Territory');

insert into "Proxies"(ip_address,type,anonymous_type,country_code,port,create_time) values
('36.6.158.252',
 'HTTPS',
 'Transparent',
 'CN'
 ,61234
 ,now())